Fix/91 bis
SolidLabResearch/generic-data-viewer-react-admin pull request #108
Opened 2024-04-22 14:51 UTC by EmilioTR

closes #91

2024-04-24 13:56 UTC, mvanbrab requested changes
Nice solution.
My comments are minor, but I'd like you to resolve them anyway.
The failing log-in.cy.js test will pass once you merged the main branch (I fixed it there).
We'll set this branch on hold until you solved #102.

2024-04-24 13:56 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +      console.error("Error executing query:", error);
This code change is not useful. I guess it's a remainder of a debugging session. Avoid writing to the console in finished code.

2024-04-24 13:56 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +        return Object.keys(filter).every((key) => result[key] === filter[key]);
Same here: although your code looks nicer, never change working code without a good reason.

2024-04-24 13:56 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +      total: parseInt(totalItems, 10),
Same here; base-10 is the default anyway...

2024-04-25 07:40 UTC, EmilioTR commented
Only the CHANGELOG.md has to be updated, appart from that everything is all right.

2024-04-25 07:51 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +    const results = await executeQuery(query);
This should be let, not const (see reassignment in line 53)

2024-04-25 07:56 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +      } catch (error) {
This doesn't make sense anymore. Remove the catch.

2024-04-25 07:58 UTC, mvanbrab commented on src/dataProvider/SparqlDataProvider.js
> +    console.error("Error adding sources from index:", error);
Remove the console.error call. Compose a new Error from your text here and the underlying error message text.

2024-04-25 14:00 UTC, mvanbrab approved these changes

2024-04-25 14:00 UTC, merged